apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-nftlb
  namespace: kube-system
spec:
  selector:
      matchLabels:
        name: kube-nftlb
  template:
    metadata:
      labels:
        name: kube-nftlb
    spec:
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
      - name: kube-nftlb
        image: kube-nftlb
        imagePullPolicy: Never
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        - mountPath: /var/config-kubernetes
          name: kubernetesconfig-volumen
        - mountPath: /var/run/docker.sock
          name: docker-sock
      volumes:
      - name: kubernetesconfig-volumen
        hostPath:
          path: /etc/kubernetes
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock

