apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-nftlb
  namespace: kube-system
  labels:
    name: kube-nftlb
spec:
  selector:
    matchLabels:
      name: kube-nftlb
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        name: kube-nftlb
    spec:
      priorityClassName: system-node-critical
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: kube-nftlb
          image: zevenet/kube-nftlb:latest
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/config-kubernetes
              name: kubernetesconfig-volumen
            - mountPath: /var/run/docker.sock
              name: docker-sock
      volumes:
        - name: kubernetesconfig-volumen
          hostPath:
            path: /etc/kubernetes
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
      serviceAccountName: kube-nftlb
