apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-nftlb
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:kube-nftlb
subjects:
  - kind: ServiceAccount
    name: kube-nftlb
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node-proxier
  apiGroup: rbac.authorization.k8s.io
